RailsClient/config/routes.rb
Rails.application.routes.draw do

  resources :dock_points do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :movement_sources do
    collection do
      get :search
    end
  end

  resources :movement_lists do
    collection do
      get :search
      get :exports
    end
    member do
      get 'movement_sources'
    end
  end

  use_doorkeeper
  resources :pick_orders

  resources :leds do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :order_cars do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :order_boxes do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :order_box_types do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :settings

  resources :units do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :colors do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :ptl_jobs

  resources :scrap_list_items do
    collection do
      match :import, to: :import, via: [:get, :post]
      get :search
    end
  end

  get 'scrap_lists/reports', to: 'scrap_lists#reports'

  resources :scrap_lists do
    member do
      get 'scrap_list_items'
      get :scrap

    end

    collection do
      match :import, to: :import, via: [:get, :post]
    end
  end

  resources :inventory_lists do
    member do
      get 'inventory_list_items'
      get :discrepancy
    end

    collection do
      get :export_total
    end
  end

  resources :inventory_list_items do
    collection do
      get :search
      match :import, to: :import, via: [:get, :post]
    end
    member do
      get :export_list_detail
      get :export_list_total
      get :lock_unlock_list
      get :store_list
      get :unstore_list
    end
  end

  resources :storages do
    collection do
      get :search
      get :panel
      get :search_storage
    end
  end

  resources :regex_categories do
    collection do
      get :regex_template
    end
  end
  resources :led_states
  resources :sys_configs
  resources :logistics_containers do
    collection do
      get :search
      match :import, to: :import, via: [:get, :post]
    end

    member do
      get :export
    end
  end

  require 'ptl/api'
  mount Ptl::Api => '/ptl'

  resources :order_items do
    collection do
      get :search
    end
  end
  resources :pick_items do
    collection do
      get :search
    end
  end

  resources :pick_lists do
    collection do
      post :print
      get :search
    end
  end

  mount ApplicationAPI => '/api'
  root :to => "welcome#index"

  devise_for :users, :controllers => {:registrations => "users/registrations"}, path: "auth", path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in'}

  resources :deliveries do
    collection do
      match :generate, to: :generate, via: [:get, :post]
      match :receive, to: :receive, via: [:get, :post]
      get :search
    end
    member do
      get :forklifts
    end
  end

  resources :files do
    collection do
      get :download
    end
  end

  resources :orders do
    collection do
      get :panel
      get :panel_list
      get :pick_panel
      get :search
      get :items
      get :pickitems
      get :filters
      get :filt
      get :picklists
      get :exports
      post :handle
      post :finish_pick
    end
    member do
      get :order_items
    end
  end

  resources :packages do
    collection do
      get :search
      get :download_quantity
    end
  end

  resources :forklifts do
    collection do
      get :search
    end
    member do
      get :packages
    end
  end

  get 'parts/import_positions', to: 'parts#import_positions'
  get 'parts/template_position', to: 'parts#template_position'
  get 'parts/download_positions', to: 'parts#download_positions'
  post 'parts/do_import_positions', to: 'parts#do_import_positions'

  resources :n_storages do
    collection do
      get :search
      match :import, to: :import, via: [:get, :post]
      match :move, to: :move, via: [:get, :post]
      match :group, to: :group, via: [:get, :post]
      match :by_whouse_we87, to: :by_whouse_we87, via: [:get, :post]
      match :by_whouse_pa, to: :by_whouse_pa, via: [:get, :post]
      get :summary
      get :exports
      get :search_by_whouse
    end

  end

  resources :part_positions do
    collection do
      post :do_import
      get :download
      get :template
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :movements do
    collection do
      get :search
    end
  end

  get 'orders/search', to: 'orders#search'

  [:locations, :whouses, :parts, :positions, :users, :deliveries, :forklifts,
   :packages, :part_types, :pick_item_filters, :orders, :modems].each do |model|
    resources model do
      collection do
        post :do_import
        get :import
        get :download
        get :template
        get :search
      end
    end
  end

  delete '/parts/delete_position/:id', to: 'parts#delete_position'

  get 'reports/movements_report', to: 'reports#movements_report'
  get 'reports/discrepancy', to: 'reports#discrepancy'
  get 'reports/orders_report', to: 'reports#orders_report'
  get 'reports/reports', to: 'reports#reports'
  post 'reports/upload_file', to: 'reports#upload_file'
  get 'reports/fors_discrepancy', to: 'reports#fors_discrepancy'

  get 'notifications', to: 'notifications#index'
  get 'notifications/orderbus', to: 'notifications#orderbus'

  resources :labels do
    collection do
      post :upload_file
      get :get_config
      get :get_config_hash
      get :get_config_version
    end
  end

  resources :locations do
    member do
      get 'users'
      get 'whouses'
      get 'destinations'
      post :add_destination
      delete 'remove_destination/:destination_id', to: :remove_destination, as: 'remove_destination'
      post 'set_default_destination/:destination_id', to: :set_default_destination, as: 'set_default_destination'
    end
  end

  resources :whouses do
    member do
      get 'positions'
    end
  end

  resources :positions do
    member do
      get 'parts'
    end
  end

  resources :syncs do
    collection do
      post :reload
    end
  end

  resources :regexes do
    collection do
      post :save
    end
  end

end

RailsClient/app/controllers/whouses_controller.rb
class WhousesController < ApplicationController
  #load_and_authorize_resource
  before_action :set_whouse, only: [:show, :edit, :update, :destroy, :positions]

  # GET /whouses
  # GET /whouses.json
  def index
    @whouses = Whouse.paginate(:page => params[:page])#all
    #@whouses = @whouses.paginate(:page=>params[:page])
  end

  # GET /whouses/1
  # GET /whouses/1.json
  def show
  end

  # GET /whouses/new
  def new
    @whouse = Whouse.new
  end

  # GET /whouses/1/edit
  def edit
  end

  # POST /whouses
  # POST /whouses.json
  def create
    @whouse = Whouse.new(whouse_params)

    respond_to do |format|
      if @whouse.save
        format.html { redirect_to @whouse, notice: 'Whouse was successfully created.' }
        format.json { render :show, status: :created, location: @whouse }
      else
        format.html { render :new }
        format.json { render json: @whouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /whouses/1
  # PATCH/PUT /whouses/1.json
  def update
    respond_to do |format|
      if @whouse.update(whouse_params)
        format.html { redirect_to @whouse, notice: 'Whouse was successfully updated.' }
        format.json { render :show, status: :ok, location: @whouse }
      else
        format.html { render :edit }
        format.json { render json: @whouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /whouses/1/whouses
  def positions
    @positions = @whouse.positions.paginate(:page => params[:page])
  end

  # DELETE /whouses/1
  # DELETE /whouses/1.json
  def destroy
    @whouse.destroy
    respond_to do |format|
      format.html { redirect_to whouses_url, notice: 'Whouse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_whouse
      @whouse = Whouse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def whouse_params
      #params[:whouse]
      params.require(:whouse).permit(:id,:name,:location_id,:is_mrp_whouse)
    end
end

RailsClient/app/helpers/whouses_helper.rb
module WhousesHelper
end

RailsClient/app/views/whouses/_form.html.erb
<%= form_for(@whouse) do |f| %>
    <% if @whouse.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@whouse.errors.count, "error") %> prohibited this whouse from being saved:</h2>

          <ul>
            <% @whouse.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="panel panel-primary">
      <div class="panel-body">
        <div class="col-sm-12" style="height: 40px;border-bottom: 1px dashed #000;">
          <div class="col-sm-3">
            <%= f.label :nr, '编 号' %>
            <%= f.text_field :nr %>
          </div>
          <div class="col-sm-3">
            <%= f.label :name, '名 称' %>
            <%= f.text_field :name %>
          </div>
          <div class="col-sm-3">
            <%= f.label :is_mrp_whouse, 'MRP 仓库' %>
            <%= f.check_box :is_mrp_whouse %>
          </div>
          <div class="col-sm-3">
            <%= f.label :location_id, '地 点' %>
            <%= f.select(:location_id, Location.all.collect { |l| [l.name, l.id] }, {include_blank: false}) %>
          </div>
        </div>
        <div class="actions">
          <%= f.submit value: '提 交', class: 'btn btn-primary', :style => 'width:200px;margin-top:20px;' %>
        </div>
      </div>
    </div>
<% end %>

RailsClient/app/views/whouses/edit.html.erb
<style>
    a:hover, a:active {
        text-decoration: none;
        background-color: white;
        color: black;
        outline: none;
    }
</style>

<div class="panel panel-default">
  <ol class="breadcrumb" style="background: transparent;padding: 20px 0 0 20px;font-size: 1.2em;">
    <li class="active">管理</li>
    <li>
      <%= link_to '仓库', whouses_path, :title => '返回仓库' %>
    </li>
    <li class="active">
      编辑仓库
      <%= link_to content_tag(:i, '', :class => 'glyphicon glyphicon-eye-open', :style => 'color:green;'), @whouse, :title => '详细' %>
    </li>
  </ol>
</div>

<%= render 'form' %>

RailsClient/app/views/whouses/index.html.erb
<h2>仓库列表</h2>

<%= link_to "新建分仓库", send("new_#{@model}_path"),:class=>'btn btn-default' %>
<%= link_to "上传/更新分仓库", send("import_#{@model.pluralize}_path") ,:class=>'btn btn-default'%>
<%= link_to "下载", send("download_#{@model.pluralize}_path"),data: { confirm: 'Are you sure?' },:class=>'btn btn-default' %>
<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @whouses %>
  </div>
  <%= will_paginate @whouses, :container => false %>
</div>
<table class="table table-bordered table-striped globle-table">
  <thead>
    <tr>
      <th>序号</th>
      <th>编号</th>
      <th>名称</th>
      <th>所属地点</th>
      <th>是MRP仓库</th>
      <th>库位</th>
      <th colspan="3">&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @whouses.each_with_index do |whouse,index| %>
      <tr>
        <td><%= index +@whouses.offset+1%>
        <td><%= whouse.id %> </td>
        <td><%= whouse.name %></td>
        <td><%= whouse.location.name if whouse.location %></td>
        <td><%= whouse.is_mrp_whouse ? '是' : '否'  %></td>
        <td><%= link_to '库位列表',positions_whouse_path(whouse) %><span class="badge pull-right"><%= whouse.positions.count%></span></td>
        <td><%= link_to '详细', whouse ,:class=>"btn btn-default"%></td>
        <td><%= link_to '编辑', edit_whouse_path(whouse),:class=>"btn btn-default" %></td>
        <td><%= link_to '删除', whouse, method: :delete, data: { confirm: '确认删除?' },:class=>"btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="digg_pagination">
  <%= will_paginate @whouses, :container => false %>
</div>
<br>

RailsClient/app/views/whouses/new.html.erb
<style>
    a:hover, a:active {
        text-decoration: none;
        background-color: white;
        color: black;
        outline: none;
    }
</style>

<div class="panel panel-default">
  <ol class="breadcrumb" style="background: transparent;padding: 20px 0 0 20px;font-size: 1.2em;">
    <li class="active">管理</li>
    <li>
      <%= link_to '仓库', whouses_path, :title => '返回仓库' %>
    </li>
    <li class="active">
      新建仓库
    </li>
  </ol>
</div>

<%= render 'form' %>

RailsClient/app/views/whouses/positions.html.erb
<style>
    a:hover, a:active {
        text-decoration: none;
        background-color: white;
        color: black;
        outline: none;
    }

    .label {
        font-size: 1em;
    }

    .table > thead > tr > th, .table > tbody > tr > td {
        text-align: center;
    }
    
    a:hover, a:active {
        text-decoration: none;
        background-color: white;
        color: black;
        outline: none;
    }
</style>


<div class="panel panel-default">
  <ol class="breadcrumb" style="background: transparent;padding: 20px 0 0 20px;font-size: 1.2em;">
    <li class="active">管理</li>
    <li>
      <%= link_to '仓库', whouses_path, :title => '返回仓库' %>
    </li>
    <li class="active">
      <span class="label label-primary"><%= @whouse.name %></span>
      库位列表
    </li>
  </ol>
</div>

<div class="col-sm-12" style="margin-bottom: 20px;">
  <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @positions %>
    </div>
    <%= will_paginate @positions, :container => false %>
  </div>
</div>

<table class="table table-bordered table-striped table-hover">
  <thead>
  <tr>
    <th>NO.</th>
    <th>编号</th>
    <th>位置详细</th>
  </tr>
  </thead>
  <tbody>
  <% @positions.each_with_index do |pos, index| %>
      <tr>
        <td><%= index+@positions.offset+1 %></td>
        <td><%= pos.nr %></td>
        <td><%= pos.detail %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="digg_pagination">
  <%= will_paginate @positions, :container => false %>
</div>

RailsClient/app/views/whouses/show.html.erb
<style>
    a:hover, a:active {
        text-decoration: none;
        background-color: white;
        color: black;
        outline: none;
    }
</style>

<div class="panel panel-default">
  <ol class="breadcrumb" style="background: transparent;padding: 20px 0 0 20px;font-size: 1.2em;">
    <li class="active">管理</li>
    <li class="active">基础信息设置</li>
    <li>
      <%= link_to '仓库', whouses_path, :title => '返回仓库' %>
    </li>
    <li class="active">
      仓库详情
    </li>
  </ol>
</div>

<div class="panel panel-primary">
  <div class="panel panel-heading">
    <div class="panel-title" style="display: flex;">
      <h3><%= @whouse.name %></h3>
      <span class="label label-info" style="height: 30px;line-height: 25px;margin-top: 20px;margin-left: 10px;"><%= @whouse.nr %></span>
    </div>
  </div>
  <div class="panel-body" style="font-size: 1.4em;">
    所属地点:
    <%= @whouse.location.name %>
  </div>
</div>