RailsClient/config/routes.rb
Rails.application.routes.draw do

  resources :dock_points do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :movement_sources do
    collection do
      get :search
    end
  end

  resources :movement_lists do
    collection do
      get :search
      get :exports
    end
    member do
      get 'movement_sources'
    end
  end

  use_doorkeeper
  resources :pick_orders

  resources :leds do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :order_cars do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :order_boxes do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :order_box_types do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :settings

  resources :units do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :colors do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :ptl_jobs

  resources :scrap_list_items do
    collection do
      match :import, to: :import, via: [:get, :post]
      get :search
    end
  end

  get 'scrap_lists/reports', to: 'scrap_lists#reports'

  resources :scrap_lists do
    member do
      get 'scrap_list_items'
      get :scrap

    end

    collection do
      match :import, to: :import, via: [:get, :post]
    end
  end

  resources :inventory_lists do
    member do
      get 'inventory_list_items'
      get :discrepancy
    end

    collection do
      get :export_total
    end
  end

  resources :inventory_list_items do
    collection do
      get :search
      match :import, to: :import, via: [:get, :post]
    end
    member do
      get :export_list_detail
      get :export_list_total
      get :lock_unlock_list
      get :store_list
      get :unstore_list
    end
  end

  resources :storages do
    collection do
      get :search
      get :panel
      get :search_storage
    end
  end

  resources :regex_categories do
    collection do
      get :regex_template
    end
  end
  resources :led_states
  resources :sys_configs
  resources :logistics_containers do
    collection do
      get :search
      match :import, to: :import, via: [:get, :post]
    end

    member do
      get :export
    end
  end

  require 'ptl/api'
  mount Ptl::Api => '/ptl'

  resources :order_items do
    collection do
      get :search
    end
  end
  resources :pick_items do
    collection do
      get :search
    end
  end

  resources :pick_lists do
    collection do
      post :print
      get :search
    end
  end

  mount ApplicationAPI => '/api'
  root :to => "welcome#index"

  devise_for :users, :controllers => {:registrations => "users/registrations"}, path: "auth", path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in'}

  resources :deliveries do
    collection do
      match :generate, to: :generate, via: [:get, :post]
      match :receive, to: :receive, via: [:get, :post]
      get :search
    end
    member do
      get :forklifts
    end
  end

  resources :files do
    collection do
      get :download
    end
  end

  resources :orders do
    collection do
      get :panel
      get :panel_list
      get :pick_panel
      get :search
      get :items
      get :pickitems
      get :filters
      get :filt
      get :picklists
      get :exports
      post :handle
      post :finish_pick
    end
    member do
      get :order_items
    end
  end

  resources :packages do
    collection do
      get :search
      get :download_quantity
    end
  end

  resources :forklifts do
    collection do
      get :search
    end
    member do
      get :packages
    end
  end

  get 'parts/import_positions', to: 'parts#import_positions'
  get 'parts/template_position', to: 'parts#template_position'
  get 'parts/download_positions', to: 'parts#download_positions'
  post 'parts/do_import_positions', to: 'parts#do_import_positions'

  resources :n_storages do
    collection do
      get :search
      match :import, to: :import, via: [:get, :post]
      match :move, to: :move, via: [:get, :post]
      match :group, to: :group, via: [:get, :post]
      match :by_whouse_we87, to: :by_whouse_we87, via: [:get, :post]
      match :by_whouse_pa, to: :by_whouse_pa, via: [:get, :post]
      get :summary
      get :exports
      get :search_by_whouse
    end

  end

  resources :part_positions do
    collection do
      post :do_import
      get :download
      get :template
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :movements do
    collection do
      get :search
    end
  end

  get 'orders/search', to: 'orders#search'

  [:locations, :whouses, :parts, :positions, :users, :deliveries, :forklifts,
   :packages, :part_types, :pick_item_filters, :orders, :modems].each do |model|
    resources model do
      collection do
        post :do_import
        get :import
        get :download
        get :template
        get :search
      end
    end
  end

  delete '/parts/delete_position/:id', to: 'parts#delete_position'

  get 'reports/movements_report', to: 'reports#movements_report'
  get 'reports/discrepancy', to: 'reports#discrepancy'
  get 'reports/orders_report', to: 'reports#orders_report'
  get 'reports/reports', to: 'reports#reports'
  post 'reports/upload_file', to: 'reports#upload_file'
  get 'reports/fors_discrepancy', to: 'reports#fors_discrepancy'

  get 'notifications', to: 'notifications#index'
  get 'notifications/orderbus', to: 'notifications#orderbus'

  resources :labels do
    collection do
      post :upload_file
      get :get_config
      get :get_config_hash
      get :get_config_version
    end
  end

  resources :locations do
    member do
      get 'users'
      get 'whouses'
      get 'destinations'
      post :add_destination
      delete 'remove_destination/:destination_id', to: :remove_destination, as: 'remove_destination'
      post 'set_default_destination/:destination_id', to: :set_default_destination, as: 'set_default_destination'
    end
  end

  resources :whouses do
    member do
      get 'positions'
    end
  end

  resources :positions do
    member do
      get 'parts'
    end
  end

  resources :syncs do
    collection do
      post :reload
    end
  end

  resources :regexes do
    collection do
      post :save
    end
  end

end

RailsClient/app/models/forklift.rb
class Forklift<Container
  default_scope { where(type: ContainerType::FORKLIFT, is_delete: 0) }

  def generate_id
    "F#{Time.now.strftime('%y%m%d%H%M%S')}"
  end

end

RailsClient/app/controllers/forklifts_controller.rb
class ForkliftsController < ApplicationController
  #load_and_authorize_resource
  before_action :set_forklift, only: [:show, :edit, :update, :destroy,:packages]

  # GET /forklifts
  # GET /forklifts.json
  def index
    @forklifts = ForkliftService.search(nil,true,current_user.location).order(created_at: :desc).paginate(:page=>params[:page])#all
    #@forklifts = @forklifts.paginate(:page=>params[:page])
  end

  # GET /forklifts/1
  # GET /forklifts/1.json
  def show
  end

  # GET /forklifts/new
  def new
    @forklift = Forklift.new
  end

  # GET /forklifts/1/edit
  def edit
  end

  # POST /forklifts
  # POST /forklifts.json
=begin
  def create
    @forklift = Forklift.new(forklift_params)

    respond_to do |format|
      if @forklift.save
        format.html { redirect_to @forklift, notice: '托盘新建成功' }
        format.json { render :show, status: :created, location: @forklift }
      else
        format.html { render :new }
        format.json { render json: @forklift.errors, status: :unprocessable_entity }
      end
    end
  end
=end

  # PATCH/PUT /forklifts/1
  # PATCH/PUT /forklifts/1.json
  def update

    #现在不能修改备货仓库了。
    respond_to do |format|
      if @forklift.update(forklift_params)

        if forklift_params.has_key? :state
          @forklift.descendants.each{|d| d.update({state: forklift_params[:state],is_dirty:true})}
        end

        format.html { redirect_to forklift_url(@forklift), notice: '托盘更新成功' }
        format.json { render :show, status: :ok, location: @forklift }
      else
        format.html { render :edit }
        format.json { render json: @forklift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forklifts/1
  # DELETE /forklifts/1.json
  def destroy
    @forklift.destroy
    respond_to do |format|
      format.html { redirect_to forklifts_url, notice: '托盘删除成功' }
      format.json { head :no_content }
    end
  end

  # GET /forklifts/1/packages
  def packages
    @packages = ForkliftPresenter.new(@forklift).packages.paginate(:page=>params[:page]).order(created_at: :desc)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_forklift
    @forklift = ForkliftService.search({id:params[:id]}).first
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def forklift_params
    #params[:forklift]
    params.require(:logistics_container).permit(:state,:remark)
  end

=begin
  def set_search_variable
    p= params[:forklift]
    @id=p[:id]
    @stocker_id=p[:stocker_id]
    @state=p[:state]
    @created_at_start=p[:created_at][:start]
    @created_at_end=p[:created_at][:end]
  end
=end
end

RailsClient/app/helpers/forklifts_helper.rb
module ForkliftsHelper
end

RailsClient/app/views/forklifts/_form.html.erb
<%= form_for(@forklift, url: forklift_path) do |f| %>
    <% if @forklift.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@forklift.errors.count, "error") %> prohibited this forklift from being saved:</h2>
          <ul>
            <% @forklift.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="panel-title">
          编辑托盘清单
        </div>
      </div>
      <div class="panel-body">
        <!--<div class="col-sm-4" style="margin-top: 10px;">-->
          <!--<%= f.label :state, '状 态' %>-->
          <!--<%= f.select(:state, MovableState.state, {include_blank: false}, :style => 'width:150px;') %>-->
        <!--</div>-->

        <div class="col-sm-4" style="margin-top: 10px;">
          <%= f.label :remark, '备 注' %>
          <%= f.text_field :remark, :style => 'width:300px;' %>
        </div>

        <div class="actions col-sm-4">
          <%= f.submit value: '提 交', class: 'btn btn-primary', :style => 'width:200px;' %>
        </div>
      </div>
    </div>
<% end %>

RailsClient/app/views/forklifts/edit.html.erb
<style>
    a:hover, a:active {
        text-decoration: none;
        background-color: white;
        color: black;
        outline: none;
    }
</style>
<div class="panel panel-default">
  <ol class="breadcrumb" style="background: transparent;padding: 20px 0 0 20px;font-size: 1.2em;">
    <li class="active">运输管理</li>
    <li class="active">发运流程</li>
    <li>
      <a href="/forklifts" title="返回托盘">托盘</a>
    </li>
    <li class="active">
      编辑托盘清单
      <%= link_to content_tag(:i, '', :class => 'glyphicon glyphicon-eye-open', :style => 'color:green;'), forklift_path(@forklift), :title => '查看托盘清单' %>
    </li>
  </ol>
</div>

<%= render 'form' %>

RailsClient/app/views/forklifts/index.html.erb
<!--<h2>托盘列表</h2>-->
<style>
    .col-sm-12 {
        height: 40px;
    }

    select {
        width: 150px;
    }

    .up_search {
        text-align: center;
        cursor: pointer;
    }

    .IconA {
        margin: 0 10px;
        font-size: 1.2em;
    }

    .IconA:hover {
        text-decoration: none;
        background-color: white;
    }

    .table > thead > tr > th, .table > tbody > tr > td {
        text-align: center;
    }
    
    a:hover, a:active {
        text-decoration: none;
        background-color: white;
        color: black;
        outline: none;
    }
</style>
<div class="panel panel-default">
  <ol class="breadcrumb" style="background: transparent;padding: 20px 0 0 20px;font-size: 1.2em;">
    <li class="active">运输管理</li>
    <li class="active">
      发运流程
    </li>
    <li class="active">
      托盘
    </li>
  </ol>
</div>

<div class="all-search">
  <form method="get" action="<%= send("search_logistics_containers_path") %>">
    <div class="col-sm-12">
      <div class="col-sm-6">
        托清单号：
        <input type="text" name="forklift[container_id]" value="<%= @forklift_container_id %>"/>
        <input type="hidden" name="forklift[container_id_fuzzy]"/>
      </div>
      <div class="col-sm-6">
        备货员工号：
        <input type="text" name="forklift[user_id]" value="<%= @forklift_user_id %>"/>
        <input type="hidden" name="forklift[user_id_fuzzy]"/>
      </div>
    </div>
    <div class="col-sm-12">
      <div class="col-sm-6">
        状  态：
        <%= select 'forklift', 'state', MovableState.state, selected: @forklift_state, include_blank: true %>
      </div>
      <div class="col-sm-6">
        创建日期： 
        <input type="text" name="forklift[created_at][start]" class="datepicker" value="<%= @forklift_created_at_start %>"/>
        ~
        <input type="text" name="forklift[created_at][end]" class="datepicker" value="<%= @forklift_created_at_end %>"/>
      </div>
    </div>


    <div class="col-sm-12">
      <div class="col-sm-10">
        <h4 style="margin-top: 0;">
          根据操作记录
          <hr style="border-bottom: 1px dashed #000;margin: -10px 0 0 120px">
        </h4>
      </div>

      <div class="col-sm-2" style="text-align: right;">
        <input type="hidden" value="forklift" name="model"/>
        <input type="hidden" value="records" name="tables"/><!--使用分号隔开，这里的表应该与上面的参数一致-->
        <input type="submit" value="查 找" class="btn btn-primary" style="width: 150px;height: 50px;margin-top: -20px;"/>
      </div>
    </div>

    <div class="col-sm-12" style="border-bottom: 1px solid #CCCCCC;">
      <div class="col-sm-3">
        员工号：
        <input type="text" name="records[impl_id]" value="<%= @records_impl_id %>"/>
        <input type="hidden" name="records[impl_id_fuzzy]"/>
      </div>
      <div class="col-sm-3">
        操 作：
        <%= select 'records', 'impl_user_type', ImplUserType.list_action_menu, selected: @records_impl_user_type, include_blank: true %>
      </div>
      <div class="col-sm-6">
        时  间：
        <input type="text" name="records[impl_time][start]" class="datepicker" value="<%= @records_impl_time_start %>"/>
        ~ <input type="text" name="records[impl_time][end]" class="datepicker" value="<%= @records_impl_time_end %>"/>
      </div>
    </div>

    <!--<div>
      <input type="hidden" value="forklift" name="model"/>
      <input type="hidden" value="records" name="tables"/>
      &lt;!&ndash;使用分号隔开，这里的表应该与上面的参数一致&ndash;&gt;
      <input type="submit" value="查找" class="btn btn-primary" name="search"/>
      &lt;!&ndash;<input type="submit" value="下载为Excel" class="btn btn-primary" data-confirm="Are you sure?" name="download"/>&ndash;&gt;
    </div>-->
  </form>
</div>

<div class="col-sm-12 up_search">
  <i class=" glyphicon glyphicon-chevron-up" title="收起搜索条件"></i>
</div>


<div class="col-sm-12" style="margin-top: -30px;margin-bottom: 20px;">
  <input type="button" value="打印托清单" class='btn btn-warning' onclick="print_forklift_list();"/>

  <% if current_user.can_edit_inventory? %>
      <%= link_to '导入离线托清单', import_logistics_containers_path, :class => "btn btn-warning", :style => 'color:white;' %>
  <% end %>
</div>

<div class="col-sm-12">
  <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @forklifts %>
    </div>
    <%= will_paginate @forklifts, :container => false %>
  </div>
</div>

<table class="table table-bordered table-striped table-hover">
  <thead>
  <tr>
    <th></th>
    <th>序号</th>
    <th>托清单号</th>
    <th>批次号</th>
    <th>状态</th>
    <th>所属运单</th>
    <th>目标仓库</th>
    <th>备注</th>
    <th>包装箱列表</th>
    <th>包装箱总数</th>
    <th>已接收包装箱数</th>
    <th>最新记录</th>
    <th colspan="2">操作</th>
  </tr>
  </thead>

  <tbody>
  <% @forklifts.each_with_index do |forklift, index| %>
      <% fpresenter = ForkliftPresenter.new(forklift) %>
      <tr>
        <td><input type="checkbox" id="<%= forklift.id %>" class='print-check'></td>
        <td><%= index+@forklifts.offset+1 %>
        <td><%= forklift.container_id %></td>
        <td><%=forklift.batch_nr%></td>
        <td><%= forklift.state_display %></td>
        <td>
          <%= link_to content_tag(:span, forklift.parent.container_id, :class => 'label label-primary', :style => 'font-size:1em;'), delivery_path(forklift.parent) if forklift.parent %>
        </td>
        <td><%= forklift.destinationable.name if forklift.destinationable %></td>
        <td><%= forklift.remark %></td>
        <td>
          <%= link_to content_tag(:span, fpresenter.packages.count, :class => 'label label-primary', :style => 'font-size:1em;'), packages_forklift_path(forklift) %>
        </td>
        <td><%= fpresenter.sum_packages %></td>
        <td><%= fpresenter.accepted_packages %></td>

        <td><%= forklift.get_records.last.display %></td>

        <td>
          <%= link_to content_tag(:i, '', :class => 'glyphicon glyphicon-eye-open', :style => 'color:green;'), forklift_path(forklift), :title => '托清单详情', :class => 'IconA' %>

          <% if current_user.permission?(:operate_delivery) %>
              <%= link_to content_tag(:i, '', :class => 'glyphicon glyphicon-pencil', :style => 'color:#4F94CD;'), edit_forklift_path(forklift), :class => 'IconA', :title => '编辑托清单' if current_user.admin? %>
          <% end %>

          <!--<%= link_to content_tag(:i, '', :class => 'glyphicon glyphicon-log-out'), {controller: 'logistics_containers', action: 'export', id: forklift.id}, class: 'IconA', :title => '导出托清单' %>-->
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="digg_pagination">
  <%= will_paginate @forklifts, :container => false %>
</div>

<script>
    $(function () {
        $(".datepicker").datetimepicker({
            lang: 'ch',
            format: 'Y-m-d H:i'
        });
    });
    init_check();

    $('.up_search').click(function () {
        var this_arrow = $(this);
        $('.all-search').slideToggle(300, function () {
            if (this_arrow.children('i').hasClass('glyphicon-chevron-up')) {
                this_arrow.children('i').attr('class', 'glyphicon glyphicon-chevron-down');
                this_arrow.children('i').attr('title', '展开搜索条件');
            } else {
                this_arrow.children('i').attr('class', 'glyphicon glyphicon-chevron-up');
                this_arrow.children('i').attr('title', '收起搜索条件');
            }
        });
    })
</script>

RailsClient/app/views/forklifts/new.html.erb
<h1>新建托盘</h1>

<%= render 'form' %>

<%= link_to '返回', forklifts_path %>

RailsClient/app/views/forklifts/packages.html.erb
<style type="text/css">
  .table > thead > tr > th, .table > tbody > tr > td {
        text-align: center;
    }
    
    a:hover, a:active {
        text-decoration: none;
        background-color: white;
        color: black;
        outline: none;
    }
    .label{
      font-size: 1em;
    }
</style>
<div class="panel panel-default">
  <ol class="breadcrumb" style="background: transparent;padding: 20px 0 0 20px;font-size: 1.2em;">
    <li class="active">运输管理</li>
    <li class="active">运输管理</li>
    <li class="active">
      发运流程
    </li>
    <li>
      <%= link_to '托盘', forklifts_path  %>
    </li>
    <li class="active">
      包装箱列表
      <span class="label label-primary"><%= @forklift.container_id%></span>
    </li>
  </ol>
</div>

<div class="col-sm-12" style="margin-bottom: 20px;">
  <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @packages %>
    </div>
    <%= will_paginate @packages, :container => false %>
  </div>
</div>

<table class="table table-bordered table-striped table-hover">
  <thead>
  <tr>
    <th>NO.</th>
    <th>唯一号</th>
    <th>收发货日期</th>
    <th>零件号</th>
    <th>零件类型</th>
    <th>数量</th>
    <th>备注</th>
    <!--<th>上架库位</th>-->
    <!--<th>状态</th>-->
  </tr>
  </thead>
  <tbody>
  <% @packages.each_with_index do |package,index|%>
      <% ppresenter = PackagePresenter.new(package)%>
      <tr>
        <td><%= index+@packages.offset+1%></td>
        <td><%= link_to package.container_id,package_path(package),:class=>'label label-primary' %></td>
        <td><%= package.package.fifo_time.blank? ? ' ' : package.package.fifo_time.localtime.strftime('%y.%m.%d %H:%M') %></td>
        <td><%=  package.package.part.nr_for_user(current_user) %></td>
        <td><%= package.package.part.type_name if package.package %></td>
        <td><%=  package.package.quantity_str %></td>
        <td><%=  package.package.remark %></td>
        <!--<td><%= ppresenter.position_nr %></td>-->
        <!--<td><%= package.state_display%></td>-->
      </tr>
  <% end%>
  </tbody>
</table>
<div class="digg_pagination">
  <%= will_paginate @packages, :container => false %>
</div>

RailsClient/app/views/forklifts/show.html.erb
<style>
    .col-sm-12 {
        height: 40px;
        line-height: 40px;
    }

    .table > thead > tr > th, .table > tbody > tr > td {
        text-align: center;
    }

    a:hover, a:active {
        text-decoration: none;
        background-color: white;
        color: black;
        outline: none;
    }

    .label {
        font-size: 1em;
    }
</style>

<% fpresenter = ForkliftPresenter.new(@forklift) %>

<div class="panel panel-default">
  <ol class="breadcrumb" style="background: transparent;padding: 20px 0 0 20px;font-size: 1.2em;">
    <li class="active">运输管理</li>
    <li class="active">发运流程</li>
    <li>
      <a href="/forklifts" title="返回托盘">托盘</a>
    </li>
    <li class="active">
      <span class="label label-primary"><%= @forklift.container_id %></span>

      <% if current_user.permission?(:operate_delivery) %>
          <%= link_to content_tag(:i, '', :class => 'glyphicon glyphicon-pencil'), edit_forklift_path, :style => 'color:steelblue;margin-left:10px;', :title => "编辑托盘" %>
      <% end %>
    </li>
  </ol>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <div class="panel-title">
      基础
    </div>
  </div>
  <div class="panel-body">
    <div class="col-sm-12">
      <div class="col-sm-4">
        状态:
        <%= @forklift.state_display %>
      </div>
      <div class="col-sm-4">
        创建时间:
        <%= fpresenter.created_at %>
      </div>
    </div>

    <div class="col-sm-12">
      <div class="col-sm-4">
        创建员工号:
        <%= @forklift.user.nr %>
      </div>
      <div class="col-sm-4">
        创建员工:
        <%= @forklift.user.name %>
      </div>
      <div class="col-sm-4">
        创建地:
        <%= @forklift.source.name %>
      </div>
    </div>

    <div class="col-sm-12">
      <div class="col-sm-4">
        目的地:
        <%= @forklift.destination.name if @forklift.destination %>
      </div>
      <div class="col-sm-4">
        所属运单:
        <%= link_to content_tag(:span, @forklift.parent.container_id, :class => 'label label-primary'), delivery_path(@forklift.parent) if @forklift.parent %>
      </div>
      <div class="col-sm-4">
        备注:
        <%= @forklift.remark %>
      </div>
    </div>

    <div class="col-sm-12">
      <!--<div class="col-sm-4">-->
        <!--备货仓库:-->
        <!--<%= @forklift.destinationable.name if @forklift.destinationable %>-->
      <!--</div>-->
      <div class="col-sm-4">
        包装箱总数:
        <%= fpresenter.sum_packages %>
      </div>
      <div class="col-sm-4">
        已接收包装箱数:
        <%= fpresenter.accepted_packages %>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <div class="panel-title">
      包装箱列表
    </div>
  </div>

  <% @packages = fpresenter.packages %>
  <table class="table table-bordered table-striped table-hover">
    <thead>
    <tr>
      <th>NO.</th>
      <th>唯一号</th>
      <th>收发货日期</th>
      <th>零件号</th>
      <th>零件类型</th>
      <th>数量</th>
      <th>备注</th>
      <!--<th>上架库位</th>-->
      <!--<th>状态</th>-->
    </tr>
    </thead>
    <tbody>
    <% @packages.each_with_index do |package, index| %>
        <% ppresenter = PackagePresenter.new(package) %>
        <tr>
          <td><%= index+1 %></td>
          <td>
            <%= link_to content_tag(:span, package.container_id, :class => 'label label-primary'), package_path(package) %>
          </td>
          <td><%= package.package.fifo_time.blank? ? ' ' : package.package.fifo_time.localtime.strftime('%y.%m.%d %H:%M') %></td>
          <td><%= package.package.part.nr_for_user(current_user) %></td>
          <td><%= package.package.part.type_name if package.package %></td>
          <td><%= package.package.quantity_str %></td>
          <td><%= package.package.remark %></td>
          <!--<td><%= ppresenter.position_nr %></td>-->
          <!--<td><%= package.state_display %></td>-->
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      操作记录
    </div>
  </div>

  <div class="panel-body">
    <% @forklift.get_records.each do |r| %>
        <div class="col-sm-4">
          <%= r.display %>
        </div>
    <% end %>
  </div>
</div>