RailsClient/config/routes.rb
Rails.application.routes.draw do

  resources :dock_points do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :movement_sources do
    collection do
      get :search
    end
  end

  resources :movement_lists do
    collection do
      get :search
      get :exports
    end
    member do
      get 'movement_sources'
    end
  end

  use_doorkeeper
  resources :pick_orders

  resources :leds do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :order_cars do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :order_boxes do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :order_box_types do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :settings

  resources :units do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :colors do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :ptl_jobs

  resources :scrap_list_items do
    collection do
      match :import, to: :import, via: [:get, :post]
      get :search
    end
  end

  get 'scrap_lists/reports', to: 'scrap_lists#reports'

  resources :scrap_lists do
    member do
      get 'scrap_list_items'
      get :scrap

    end

    collection do
      match :import, to: :import, via: [:get, :post]
    end
  end

  resources :inventory_lists do
    member do
      get 'inventory_list_items'
      get :discrepancy
    end

    collection do
      get :export_total
    end
  end

  resources :inventory_list_items do
    collection do
      get :search
      match :import, to: :import, via: [:get, :post]
    end
    member do
      get :export_list_detail
      get :export_list_total
      get :lock_unlock_list
      get :store_list
      get :unstore_list
    end
  end

  resources :storages do
    collection do
      get :search
      get :panel
      get :search_storage
    end
  end

  resources :regex_categories do
    collection do
      get :regex_template
    end
  end
  resources :led_states
  resources :sys_configs
  resources :logistics_containers do
    collection do
      get :search
      match :import, to: :import, via: [:get, :post]
    end

    member do
      get :export
    end
  end

  require 'ptl/api'
  mount Ptl::Api => '/ptl'

  resources :order_items do
    collection do
      get :search
    end
  end
  resources :pick_items do
    collection do
      get :search
    end
  end

  resources :pick_lists do
    collection do
      post :print
      get :search
    end
  end

  mount ApplicationAPI => '/api'
  root :to => "welcome#index"

  devise_for :users, :controllers => {:registrations => "users/registrations"}, path: "auth", path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in'}

  resources :deliveries do
    collection do
      match :generate, to: :generate, via: [:get, :post]
      match :receive, to: :receive, via: [:get, :post]
      get :search
    end
    member do
      get :forklifts
    end
  end

  resources :files do
    collection do
      get :download
    end
  end

  resources :orders do
    collection do
      get :panel
      get :panel_list
      get :pick_panel
      get :search
      get :items
      get :pickitems
      get :filters
      get :filt
      get :picklists
      get :exports
      post :handle
      post :finish_pick
    end
    member do
      get :order_items
    end
  end

  resources :packages do
    collection do
      get :search
      get :download_quantity
    end
  end

  resources :forklifts do
    collection do
      get :search
    end
    member do
      get :packages
    end
  end

  get 'parts/import_positions', to: 'parts#import_positions'
  get 'parts/template_position', to: 'parts#template_position'
  get 'parts/download_positions', to: 'parts#download_positions'
  post 'parts/do_import_positions', to: 'parts#do_import_positions'

  resources :n_storages do
    collection do
      get :search
      match :import, to: :import, via: [:get, :post]
      match :move, to: :move, via: [:get, :post]
      match :group, to: :group, via: [:get, :post]
      match :by_whouse_we87, to: :by_whouse_we87, via: [:get, :post]
      match :by_whouse_pa, to: :by_whouse_pa, via: [:get, :post]
      get :summary
      get :exports
      get :search_by_whouse
    end

  end

  resources :part_positions do
    collection do
      post :do_import
      get :download
      get :template
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :movements do
    collection do
      get :search
    end
  end

  get 'orders/search', to: 'orders#search'

  [:locations, :whouses, :parts, :positions, :users, :deliveries, :forklifts,
   :packages, :part_types, :pick_item_filters, :orders, :modems].each do |model|
    resources model do
      collection do
        post :do_import
        get :import
        get :download
        get :template
        get :search
      end
    end
  end

  delete '/parts/delete_position/:id', to: 'parts#delete_position'

  get 'reports/movements_report', to: 'reports#movements_report'
  get 'reports/discrepancy', to: 'reports#discrepancy'
  get 'reports/orders_report', to: 'reports#orders_report'
  get 'reports/reports', to: 'reports#reports'
  post 'reports/upload_file', to: 'reports#upload_file'
  get 'reports/fors_discrepancy', to: 'reports#fors_discrepancy'

  get 'notifications', to: 'notifications#index'
  get 'notifications/orderbus', to: 'notifications#orderbus'

  resources :labels do
    collection do
      post :upload_file
      get :get_config
      get :get_config_hash
      get :get_config_version
    end
  end

  resources :locations do
    member do
      get 'users'
      get 'whouses'
      get 'destinations'
      post :add_destination
      delete 'remove_destination/:destination_id', to: :remove_destination, as: 'remove_destination'
      post 'set_default_destination/:destination_id', to: :set_default_destination, as: 'set_default_destination'
    end
  end

  resources :whouses do
    member do
      get 'positions'
    end
  end

  resources :positions do
    member do
      get 'parts'
    end
  end

  resources :syncs do
    collection do
      post :reload
    end
  end

  resources :regexes do
    collection do
      post :save
    end
  end

end

RailsClient/app/models/type/report_type.rb
class ReportType
  Entry = 0
  Removal = 1

  def self.display type
    case type
      when Entry
        '收货'
      when Removal
        '发货'
    end
  end

  def self.list
    data = []
    self.constants.each do |c|
      v = self.const_get(c.to_s)
      data << [self.display(v),v]
    end
    data
  end
end

RailsClient/app/helpers/reports_helper.rb
require 'csv'

module ReportsHelper
  def self.gen_title type,start_t,end_t,location_id,sub_title=nil
    "#{Time.parse(start_t).strftime("%Y-%m-%d")}~#{Time.parse(end_t).strftime("%Y-%m-%d")} #{Location.find_by_id(location_id).name} #{ReportType.display(type.to_i)}#{sub_title}报表"
  end

  def self.csv_filter file
    res_hash = {}
    jsfile = JSON.parse(file)
    f = FileData.new(jsfile)
    fors_data = []
    CSV.foreach(f.full_path, headers: true,col_sep: ';') do |row|
      _params = {}
      fors_sys_keys.each do |key|
        if row[key].is_number?
          _params[key] = row[key].to_i.to_s
        else
          _params[key] = row[key]
        end
      end
      fors_data << _params
    end

    fors_data.each {|fd|
      if res_hash[fd["PartNr."]+fd["Warehouse"]].nil?
        res_hash[fd["PartNr."]+fd["Warehouse"]] = {"PartNr." => fd["PartNr."],"Warehouse"=>fd["Warehouse"],"Amount"=>0}
      end
      res_hash[fd["PartNr."]+fd["Warehouse"]]["Amount"] = res_hash[fd["PartNr."]+fd["Warehouse"]]["Amount"] + fd["Quantity"].to_f
    }
    return res_hash.sort_by {|key,value| value["Warehouse"]}

    return res_hash
  end

  def self.xlsx_filter file
    res_hash = {}
    jsfile = JSON.parse(file)
    f = FileData.new(jsfile)
    book = Roo::Excelx.new f.full_path

    book.default_sheet = book.sheets.first
    headers = []
    book.row(1).each {|header|
      headers << header
    }

    fors_data = []

    2.upto(book.last_row) do |line|
      params = {}
      headers.each_with_index{|key,i|
        params[key] = book.cell(line,i+1).to_s
      }

      insert = true
      _params = {}
      fors_sys_keys.each {|key|
        if insert && (params[key].nil? || params[key].to_s.blank?)
          insert = false
          break
        end

        if params[key].is_number?
          _params[key] = params[key].to_i.to_s
        else
          _params[key] = params[key]
        end
      }
      fors_data << _params
    end
    puts fors_data

    fors_data.each {|fd|
      if res_hash[fd["PartNr."]+fd["Warehouse"]].nil?
        res_hash[fd["PartNr."]+fd["Warehouse"]] = {"PartNr." => fd["PartNr."],"Warehouse"=>fd["Warehouse"],"Amount"=>0}
      end
      res_hash[fd["PartNr."]+fd["Warehouse"]]["Amount"] = res_hash[fd["PartNr."]+fd["Warehouse"]]["Amount"] + fd["Quantity"].to_f
    }
    return res_hash.sort_by {|key,value| value["Warehouse"]}
  end

  def self.fors_xlsx_filter file
    res_hash = {}
    jsfile = JSON.parse(file)
    f = FileData.new(jsfile)
    book = Roo::Excelx.new f.full_path

    book.default_sheet = book.sheets.first
    headers = []
    book.row(1).each {|header|
      headers << header
    }

    fors_data = []

    2.upto(book.last_row) do |line|
      params = {}
      headers.each_with_index{|key,i|
        params[key] = book.cell(line,i+1).to_s
      }

      insert = true
      _params = {}
      fors_pa87_keys.each {|key|
        if insert && (params[key].nil? || params[key].to_s.blank?)
          insert = false
          break
        end

        if params[key].is_number?
          _params[key] = params[key].to_i.to_s
        else
          _params[key] = params[key]
        end
      }
      fors_data << _params unless _params.blank?
    end

    puts '-----------------------------'
    puts fors_data

    fors_data.each {|fd|
      if res_hash[fd["Partnumber"]+fd["Location"]+fd["FIFO-Date"]].nil?
        res_hash[fd["Partnumber"]+fd["Location"]+fd["FIFO-Date"]] = {
            "Partnumber" => fd["Partnumber"],
            "Whouse" => fd["Whouse"],
            "Location" => fd["Location"],
            "FIFO-Date" => fd["FIFO-Date"],
            "Stock" => fd["Stock"].to_f,
            "WMS-Stock" => NStorage.stock_by_part_position_fifo(fd["Partnumber"], fd["Whouse"],fd["Location"],fd["FIFO-Date"])
        }
      else
        res_hash[fd["Partnumber"]+fd["Location"]+fd["FIFO-Date"]]["Stock"] = res_hash[fd["Partnumber"]+fd["Location"]+fd["FIFO-Date"]]["Stock"].to_f + fd["Stock"].to_f
      end
    }

    p res_hash
    return res_hash.sort_by {|key,value| value["FIFO-Date"]}
  end

  private

  def self.fors_pa87_keys
    ["Partnumber", "Whouse", "Location", "FIFO-Date", "Stock"]
  end

  def self.fors_sys_keys
    ["PartNr.","Warehouse","Quantity"]
  end
end

RailsClient/app/views/reports/_result.html.erb
<style>
    .table > thead > tr > th, .table > tbody > tr > td {
        text-align: center;
    }
</style>
<table class="table table-striped table-bordered table-hover">
  <thead>
  <tr>
    <th>No.</th>
    <th>零件号</th>
    <th>数量</th>
    <!--<th>箱数</th>-->
    <th>地点</th>
    <!--<th>状态</th>-->
  </tr>
  </thead>
  <tbody>
  <% @packages.each_with_index do |p, index| %>
      <tr>
        <td><%= index+1 %></td>
        <% if part=Part.find_by_id(p['part_id']) %>
            <td><%= part.nr %></td>
        <% else %>
            <td></td>
        <% end %>
        <td><%= p['count'] %></td>
        <!--<td><%= p['box'] %></td>-->
        <% if location=Location.find_by_id(p['whouse']) %>
            <td><%=  location.name %></td>
        <% else %>
            <td></td>
        <% end %>
        <!--<td><%= MovableState.display(p['state']) %></td>-->
      </tr>
  <% end %>
  </tbody>
</table>

RailsClient/app/views/reports/discrepancy.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <h2>差异报表</h2>
    导入报表,选择报表所属位置,时间范围,系统根据报表自动计算差异,可以选择在网页或者直接导出xlsx格式的文档进行查看
  </div>
  <div class="panel-body">
    <br/>

    <div>
      <script type="text/javascript">
          $(function () {
              data_upload("#item-data-uploader", false, function (data) {
                  if (data.result) {
                      $("#file").val(JSON.stringify(data.content));
                      $("#item-data-uploader-preview > span[info]").html("文件上传成功");
                  } else {
                      $("#file").val('');
                  }
              });
          });
          function submitForm() {
              if ($("#file").val().length > 0)
                  document.forms[0].submit();
              else
                  alert('请上传文件');
          }
      </script>
      <% if current_user.can_edit_inventory? %>
          <div>
            <span>上传报表：</span>
            <input id="item-data-uploader" type="file" name="files[]" data-url="/reports/upload_file">

            <div class="abstractblock" id="item-data-uploader-preview" style="<%= "display:none" if @file.nil? %>;">
              <% if @file %>
                  <span>文件：<%= @file["data"]["original_filename"] %></span>
                  <br>
                  <span info>文件上传成功</span>
              <% end %>
            </div>
          </div>
      <% end %>
    </div>
    <div>
      <form method="get" action="<%= reports_discrepancy_path %>">
        <div>
          <span class="label label-info">报表类型:</span>
          <%= select_tag(:type, options_for_select(ReportType.list, @type), include_blank: false) %>
          <span class="label label-info">地点:</span>
          <%= select_tag(:location_id, options_for_select(Location.list_menu(current_user), @location_id), include_blank: false) %>
          <span class="label label-info">时间范围:</span>
          <input type="text" name="received_date_start" class="datepicker" value="<%= @date_start %>"/>
          ~ <input type="text" name="received_date_end" class="datepicker" value="<%= @date_end %>"/>

          <span class="label label-info">显示方式:</span>
          <%= select_tag :format, options_for_select([["Web", "html"], ["Excel File(MS 07 or later)", "xlsx"]], "html") %>
          <input type="hidden" id="file" name="file" value="<%= @jsonfile %>">
          <input type="button" value="确定" class="btn btn-warning" name="commit" onclick="submitForm()"/>
        </div>
      </form>
    </div>
  </div>
  <br/>

  <div class="alert alert-success" role="alert">
    <p><%= @title %></p>
  </div>
  <table class="table table-striped table-condensed table-hover">
    <thead>
    <tr>
      <th>编号</th>
      <th>零件号</th>
      <th>部门</th>
      <th>报表数量</th>
      <th>系统数量</th>
      <th>差异值</th>
    </tr>
    </thead>
    <tbody>
    <% i = 0 %>
    <% @results.each do |key, value| %>
        <tr>
          <td><%= i+1 %>
            <% i=i+1 %></td>
          <td><span class="label label-info"><%= value["PartNr."] %></span></td>
          <td><%= value["Warehouse"] %></td>
          <td><span class="badge"><%= value["Amount"] %></span></td>
          <td><span class="badge"><%= @packages[key].nil? ? 0 : @packages[key]["Amount"] %></span></td>
          <td>
            <% d = @packages[key].nil? ? value["Amount"] : value["Amount"] - @packages[key]["Amount"] %>
            <% if d > 0 %>
                <span class="label label-danger"><%= d %></span>
            <% elsif d < 0 %>
                <span class="label label-warning"><%= d %></span>
            <% else %>
                <span class="label label-primary"><%= d %></span>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%%>

<script>
    $(function () {
        $(".datepicker").datetimepicker({
            lang: 'ch',
            format: 'Y-m-d H:i'
        });
    });
    init_check();
</script>

RailsClient/app/views/reports/fors_discrepancy.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <h2>差异报表</h2>
    导入Force报表,系统根据报表自动计算差异,可以选择在网页或者直接导出xlsx格式的文档进行查看
  </div>
  <div class="panel-body">
    <br/>
    <div>
      <script type="text/javascript">
          $(function () {
              data_upload("#item-data-uploader", false, function (data) {
                  if (data.result) {
                      $("#file").val(JSON.stringify(data.content));
                      $("#item-data-uploader-preview > span[info]").html("文件上传成功");
                  } else {
                      $("#file").val('');
                  }
              });
          });
          function submitForm() {
              if ($("#file").val().length > 0)
                  document.forms[0].submit();
              else
                  alert('请上传文件');
          }
      </script>
      <div>
        <span>上传报表：</span>
        <input id="item-data-uploader" type="file" name="files[]" data-url="/reports/upload_file">
        <div class="abstractblock" id="item-data-uploader-preview" style="<%= "display:none" if @file.nil? %>;">
          <% if @file %>
              <span>文件：<%= @file["data"]["original_filename"] %></span>
              <br>
              <span info>文件上传成功</span>
          <% end%>
        </div>
      </div>

      <div><a href="/files/download?folder=template&file=ForsTemplate.xlsx">下载模板</a></div>
    </div>
    <div>
      <form method="get" action="<%= reports_fors_discrepancy_path %>">
        <div>
          <span class="label label-info">显示方式:</span>
          <%= select_tag :format, options_for_select([["Web", "html"],["Excel File(MS 07 or later)", "xlsx"]], "html") %>
          <input type="hidden" id="file" name="file" value="<%= @jsonfile%>">
          <input type="button" value="确定" class="btn btn-warning" name="commit" onclick="submitForm()"/>
        </div>
      </form>
    </div>
  </div>
  <br/>
  <div class="alert alert-success" role="alert">
    <p><%= @title%></p>
  </div>
  <table class="table table-striped table-condensed table-hover">
    <thead>
    <tr>
      <th>编号</th>
      <th>零件号</th>
      <th>仓库</th>
      <th>库位</th>
      <th>FIFO</th>

      <th>系统数量</th>
      <th>报表数量</th>
      <th>差异值</th>
    </tr>
    </thead>
    <tbody>
    <% i = 0%>
    <% @results.each do |key,value| %>
        <tr>
          <td><%= i+1 %><% i=i+1%></td>
          <td><span class="label label-info"><%= value["Partnumber"]%></span></td>
          <td><%= value["Whouse"]%></td>
          <td><span class="badge"><%= value["Location"]%></span></td>
          <td><span class="badge"><%= value["FIFO-Date"]%></span></td>
          <td><span class="badge"><%= value["WMS-Stock"]%></span></td>
          <td><span class="badge"><%= value["Stock"]%></span></td>
          <td>
            <% d =  value["WMS-Stock"] - value["Stock"]%>
            <% if d > 0%>
                <span class="label label-danger"><%= d %></span>
            <% elsif d < 0%>
                <span class="label label-warning"><%= d %></span>
            <% else%>
                <span class="label label-primary"><%= d %></span>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%%>

<script>
    $(function () {
        $(".datepicker").datetimepicker({
            lang: 'ch',
            format: 'Y-m-d H:i'
        });
    });
    init_check();
</script>

RailsClient/app/views/reports/inventory_list_discrepancy.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <h2>盘点差异报表</h2>
  </div>
  <div class="panel-body">
    <br/>
    <div>
      <script type="text/javascript">
          $(function () {
              
          });
          
      </script>
     
    </div>
    <div>
      <form method="get" action="<%= reports_inventory_list_discrepancy_path %>">
          <div>
            <span class="label label-info">盘点清单:</span>
			<% inventory_lists_array = InventoryList.all.map { |inventory_list| [inventory_list.name, inventory_list.id]}%>
            <%= select_tag(:inventory_list_id,options_for_select(inventory_lists_array),include_blank: false)%>
            
            <span class="label label-info">显示方式:</span>
            <%= select_tag :format, options_for_select([["Web", "html"],["Excel File(MS 07 or later)", "xlsx"]], "html") %>
            <input type="hidden" id="file" name="file" value="<%= @jsonfile%>">
            <input type="button" value="确定" class="btn btn-warning" name="commit" onclick="submitForm()"/>
          </div>
      </form>
    </div>
  </div>
  <br/>
  <div class="alert alert-success" role="alert">
    <p><%= @title%></p>
  </div>
  <table class="table table-striped table-condensed table-hover">
    <thead>
    <tr>
      <th>编号</th>
      <th>零件号</th>
      <th>库存数量</th>
      <th>盘点数量</th>
      <th>差异值</th>
    </tr>
    </thead>
    <tbody>
    
    </tbody>
  </table>
</div>

<%%>

RailsClient/app/views/reports/movements_report.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <h2>出入库报表</h2>
    入库与出库的统计报表.
  </div>
</div>
<div class="panel-body">
  <br/>
  <!--Form-->
  <form method="get" path="<%= reports_reports_path%>">
  <span>零件号：
              <input type="text" name="part_id" value="<%= @part_id %>"/>
            </span>
    <span class="label label-info">报表类型:</span>
    <%= select_tag(:type,options_for_select(MovementType.list,@type),include_blank: false)%>
    <span class="label label-info">仓库:</span>
    <%= select_tag(:whouse_id, options_for_select(Whouse.all.collect{|w| [w.name, w.id]}, @whouse_id), include_blank: false) %>
    <span class="label label-info">创建时间:</span>
    <input id="date-start" type="text" name="date_start" class="datepicker" value="<%= @date_start %>"/>
    ~ <input id="date-end" type="text" name="date_end" class="datepicker" value="<%= @date_end %>"/>
    <span class="label label-info">显示方式:</span>
    <%= select_tag :format, options_for_select([["Web", "html"],["Excel File(MS 07 or later)", "xlsx"]], "html") %>
    <input type="submit" value="汇总" class="btn btn-warning" name="commit" onclick="submitForm()"/>
    <input type="submit" value="详细" class="btn btn-warning" name="commit" onclick="submitForm()"/>
  </form>
</div>
<!--Form-->
<div class="alert alert-success" role="alert">
  <p><%= @title%></p>
</div>


<table class="table table-striped table-condensed table-hover">
  <thead>
  <tr>
    <th>No.</th>
    <th>唯一码</th>
    <th>零件号</th>
    <th>数量</th>
    <th>仓库</th>

  </tr>
  </thead>
  <tbody>
  <% @movements.each_with_index do |p, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td>
          <% if @commit_value == "详细" %>
              <%= p.packageId %>
          <% else %>
              <%= %>
          <% end %>
        </td>
        <td><%= p.partNr %></td>
        <td><%= p.total_qty %></td>
        <td><%= p.wh_id %></td>

      </tr>
  <% end %>
  </tbody>
</table>

<% content_for :javascript_includes do %>
    <%= javascript_include_tag "bootstrap-select" %>
    <%= javascript_include_tag "treport" %>
<% end %>

<script>
    $(document).ready(function(){
        $(".datepicker").datetimepicker({
            lang: 'ch',
            format: 'Y-m-d H:i'
        });
        $('.selectpicker').selectpicker();
        $('.selectpicker').selectpicker('val', 'Mustard');
        $('.selectpicker').selectpicker('render');
    });
</script>

RailsClient/app/views/reports/orders_report.html.erb
<style>
    .col-sm-12 {
        height: 40px;
    }

    .table > thead > tr > th, .table > tbody > tr > td {
        text-align: center;
    }
</style>
<div class="panel panel-warning">
  <div class="panel-heading" style="display: flex;">
    <h3>要货报表</h3>
    <h5 style="margin-top: 25px;margin-left: 20px;">包括要货，缺货</h5>
  </div>

  <div class="panel-body">
    <form method="get" action="<%= reports_orders_report_path %>">
      <div class="col-sm-12" style="border-bottom: 1px dashed #000;">
        <div class="col-sm-6">
          <span class="label label-info">地点:</span>
          <%= select_tag(:source_location_id, options_for_select(Location.all.collect { |l| [l.name, l.id] }, @source_location_id), include_blank: false) %>
        </div>
        <div class="col-sm-6">
          <span class="label label-info">要货时间:</span>
          <input type="text" name="date_start" class="datepicker" value="<%= @date_start %>"/>
          ~ <input type="text" name="date_end" class="datepicker" value="<%= @date_end %>"/>
        </div>
      </div>

      <div class="col-sm-12" style="margin-bottom: -10px;margin-top: 10px;">
        <div class="col-sm-6">
          <span class="label label-info">显示方式:</span>
          <%= select_tag :format, options_for_select([["Web", "html"], ["Excel File(MS 07 or later)", "xlsx"]], "html") %>
        </div>
        <div class="col-sm-6">
          <input type="submit" style="width: 200px;" value="生成" class="btn btn-warning" name="commit"/>
        </div>
      </div>
    </form>
  </div>
</div>

<table class="table table-striped table-bordered table-hover" style="margin-top: -20px;">
  <thead>
  <tr>
    <th>No.</th>
    <th>零件号</th>
    <th>总数</th>
    <th>箱数</th>
    <th>部门</th>
    <th>要货人</th>
    <th>状态</th>
    <th>已发货总数</th>
    <th>已发运箱数</th>
    <th>差异数（要货总数-已发运总数）</th>
  </tr>
  </thead>
  <tbody>
  <% @order_items.each_with_index do |o, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= o.part_id %></td>
        <td><%= o.total %></td>
        <td><%= o.box_count %></td>
        <td><%= o.whouse_id %></td>
        <td><%= o.user_id %></td>
        <% case o.state %>
        <% when OrderItemState::INIT %>
            <td><span class="label label-warning">未处理</span></td>
        <% when OrderItemState::OUT_OF_STOCK %>
            <td><span class="label label-danger">缺货</span></td>
        <% when OrderItemState::FINISHED %>
            <td><span class="label label-info">完成备货</span></td>
        <% end %>
        <% unless @removal_packages["#{o.part_id}#{o.whouse_id}"].nil? %>
            <td>
              <span class="label label-info"><%= @removal_packages["#{o.part_id}#{o.whouse_id}"]['count'] %></span>
            </td>
            <td>
              <span class="label label-info"><%= @removal_packages["#{o.part_id}#{o.whouse_id}"]['box'] %></span>
            </td>
            <td>
              <span class="label label-warning">
                <%= @all_orders["#{o.part_id}#{o.whouse_id}"] - @removal_packages["#{o.part_id}#{o.whouse_id}"]['count'] %>
              </span>
            </td>
        <% else %>
            <td></td>
            <td></td>
            <td></td>
        <% end %>
        <% @removal_packages["#{o.part_id}#{o.whouse_id}"] = nil %>
      </tr>
  <% end %>
  </tbody>
</table>

<script>
    $(function () {
        $(".datepicker").datetimepicker({
            lang: 'ch',
            format: 'Y-m-d H:i'
        });
    });
    init_check();
</script>