RailsClient/config/routes.rb
Rails.application.routes.draw do

  resources :dock_points do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :movement_sources do
    collection do
      get :search
    end
  end

  resources :movement_lists do
    collection do
      get :search
      get :exports
    end
    member do
      get 'movement_sources'
    end
  end

  use_doorkeeper
  resources :pick_orders

  resources :leds do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :order_cars do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :order_boxes do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :order_box_types do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :settings

  resources :units do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :colors do
    collection do
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :ptl_jobs

  resources :scrap_list_items do
    collection do
      match :import, to: :import, via: [:get, :post]
      get :search
    end
  end

  get 'scrap_lists/reports', to: 'scrap_lists#reports'

  resources :scrap_lists do
    member do
      get 'scrap_list_items'
      get :scrap

    end

    collection do
      match :import, to: :import, via: [:get, :post]
    end
  end

  resources :inventory_lists do
    member do
      get 'inventory_list_items'
      get :discrepancy
    end

    collection do
      get :export_total
    end
  end

  resources :inventory_list_items do
    collection do
      get :search
      match :import, to: :import, via: [:get, :post]
    end
    member do
      get :export_list_detail
      get :export_list_total
      get :lock_unlock_list
      get :store_list
      get :unstore_list
    end
  end

  resources :storages do
    collection do
      get :search
      get :panel
      get :search_storage
    end
  end

  resources :regex_categories do
    collection do
      get :regex_template
    end
  end
  resources :led_states
  resources :sys_configs
  resources :logistics_containers do
    collection do
      get :search
      match :import, to: :import, via: [:get, :post]
    end

    member do
      get :export
    end
  end

  require 'ptl/api'
  mount Ptl::Api => '/ptl'

  resources :order_items do
    collection do
      get :search
    end
  end
  resources :pick_items do
    collection do
      get :search
    end
  end

  resources :pick_lists do
    collection do
      post :print
      get :search
    end
  end

  mount ApplicationAPI => '/api'
  root :to => "welcome#index"

  devise_for :users, :controllers => {:registrations => "users/registrations"}, path: "auth", path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in'}

  resources :deliveries do
    collection do
      match :generate, to: :generate, via: [:get, :post]
      match :receive, to: :receive, via: [:get, :post]
      get :search
    end
    member do
      get :forklifts
    end
  end

  resources :files do
    collection do
      get :download
    end
  end

  resources :orders do
    collection do
      get :panel
      get :panel_list
      get :pick_panel
      get :search
      get :items
      get :pickitems
      get :filters
      get :filt
      get :picklists
      get :exports
      post :handle
      post :finish_pick
    end
    member do
      get :order_items
    end
  end

  resources :packages do
    collection do
      get :search
      get :download_quantity
    end
  end

  resources :forklifts do
    collection do
      get :search
    end
    member do
      get :packages
    end
  end

  get 'parts/import_positions', to: 'parts#import_positions'
  get 'parts/template_position', to: 'parts#template_position'
  get 'parts/download_positions', to: 'parts#download_positions'
  post 'parts/do_import_positions', to: 'parts#do_import_positions'

  resources :n_storages do
    collection do
      get :search
      match :import, to: :import, via: [:get, :post]
      match :move, to: :move, via: [:get, :post]
      match :group, to: :group, via: [:get, :post]
      match :by_whouse_we87, to: :by_whouse_we87, via: [:get, :post]
      match :by_whouse_pa, to: :by_whouse_pa, via: [:get, :post]
      get :summary
      get :exports
      get :search_by_whouse
    end

  end

  resources :part_positions do
    collection do
      post :do_import
      get :download
      get :template
      get :search
      match :import, action: :import, via: [:get, :post]
    end
  end

  resources :movements do
    collection do
      get :search
    end
  end

  get 'orders/search', to: 'orders#search'

  [:locations, :whouses, :parts, :positions, :users, :deliveries, :forklifts,
   :packages, :part_types, :pick_item_filters, :orders, :modems].each do |model|
    resources model do
      collection do
        post :do_import
        get :import
        get :download
        get :template
        get :search
      end
    end
  end

  delete '/parts/delete_position/:id', to: 'parts#delete_position'

  get 'reports/movements_report', to: 'reports#movements_report'
  get 'reports/discrepancy', to: 'reports#discrepancy'
  get 'reports/orders_report', to: 'reports#orders_report'
  get 'reports/reports', to: 'reports#reports'
  post 'reports/upload_file', to: 'reports#upload_file'
  get 'reports/fors_discrepancy', to: 'reports#fors_discrepancy'

  get 'notifications', to: 'notifications#index'
  get 'notifications/orderbus', to: 'notifications#orderbus'

  resources :labels do
    collection do
      post :upload_file
      get :get_config
      get :get_config_hash
      get :get_config_version
    end
  end

  resources :locations do
    member do
      get 'users'
      get 'whouses'
      get 'destinations'
      post :add_destination
      delete 'remove_destination/:destination_id', to: :remove_destination, as: 'remove_destination'
      post 'set_default_destination/:destination_id', to: :set_default_destination, as: 'set_default_destination'
    end
  end

  resources :whouses do
    member do
      get 'positions'
    end
  end

  resources :positions do
    member do
      get 'parts'
    end
  end

  resources :syncs do
    collection do
      post :reload
    end
  end

  resources :regexes do
    collection do
      post :save
    end
  end

end

RailsClient/app/models/delivery.rb
class Delivery < Container
  default_scope { where(type: ContainerType::DELIVERY) }
  has_many :delivery_pick_lists,dependent: :destroy
  has_many :pick_lists,through: :delivery_pick_lists
  def generate_id
    "D#{Time.now.strftime('%y%m%d%H%M%S')}"
  end

end

RailsClient/app/helpers/deliveries_helper.rb
require 'action_view'

module DeliveriesHelper
  def self.transfer_old_deliveries ids

    ds = Old::ODelivery.where(id:ids)
    begin
      ds.each_with_index do |od, index|
        ActiveRecord::Base.transaction do
          #create Delivery Container
          #puts "#{idx}-#{index}"
          d = Delivery.create({
                                  id: od.id,
                                  remark: od.remark,
                                  user_id: od.user_id,
                                  location_id: od.user.location_id,
                                  created_at: od.created_at,
                                  updated_at: od.updated_at,
                                  is_delete: od.is_delete,
                                  is_new: od.is_new,
                                  is_dirty: od.is_dirty
                              })


          dlc = d.logistics_containers.build(source_location_id: od.user.location_id, user_id: od.user_id, remark: od.remark)
          dlc.destinationable = od.destination
          dlc.des_location_id = od.destination_id

          destination = od.destination

          default_sender = User.where({role_id: Role.sender}).first
          default_receiver = User.where({role_id: Role.receiver}).first
          user_id = nil
          #change state
          #注意每一个record的时间，应该和od的时间一致，或者尽量保持一致
          case od.state
            when DeliveryState::ORIGINAL
              dlc.state = MovableState::INIT
            when DeliveryState::WAY
              dlc.state = MovableState::WAY
              #*record dispatch
              impl_time = od.delivery_date.nil? ? od.created_at : od.delivery_date
              Record.create({recordable: dlc, destinationable: dlc.destinationable, impl_id: od.user_id, impl_user_type: ImplUserType::SENDER, impl_action: 'dispatch', impl_time: impl_time, is_new: od.is_new, is_delete: od.is_delete, is_dirty: od.is_dirty})
            when DeliveryState::DESTINATION
              dlc.state = MovableState::ARRIVED
              #*record dispatch
              impl_time = od.delivery_date.nil? ? od.created_at : od.delivery_date
              Record.create({recordable: dlc, destinationable: dlc.destinationable, impl_id: od.user_id, impl_user_type: ImplUserType::SENDER, impl_action: 'dispatch', impl_time: impl_time, is_new: od.is_new, is_delete: od.is_delete, is_dirty: od.is_dirty})
              #*record receive
              impl_time = od.received_date.nil? ? od.updated_at : od.received_date
              user_id = od.receiver_id.nil? ? default_receiver : od.receiver_id
              Record.create({recordable: dlc, destinationable: dlc.destinationable, impl_id: user_id, impl_user_type: ImplUserType::RECEIVER, impl_action: 'receive', impl_time: impl_time, is_new: od.is_new, is_delete: od.is_delete, is_dirty: od.is_dirty})
            when DeliveryState::RECEIVED
              dlc.state = MovableState::CHECKED
              #*record dispatch
              impl_time = od.delivery_date.nil? ? od.created_at : od.delivery_date
              Record.create({recordable: dlc, destinationable: dlc.destinationable, impl_id: od.user_id, impl_user_type: ImplUserType::SENDER, impl_action: 'dispatch', impl_time: impl_time, is_new: od.is_new, is_delete: od.is_delete, is_dirty: od.is_dirty})
              #*record receive
              impl_time = od.received_date.nil? ? od.updated_at : od.received_date
              user_id = od.receiver_id.nil? ? default_receiver : od.receiver_id
              Record.create({recordable: dlc, destinationable: dlc.destinationable, impl_id: user_id, impl_user_type: ImplUserType::RECEIVER, impl_action: 'receive', impl_time: impl_time, is_new: od.is_new, is_delete: od.is_delete, is_dirty: od.is_dirty})
              #*record check
              impl_time = od.received_date.nil? ? od.updated_at : od.received_date
              user_id = od.receiver_id.nil? ? default_receiver : od.receiver_id
              Record.create({recordable: dlc, destinationable: dlc.destinationable, impl_id: user_id, impl_user_type: ImplUserType::EXAMINER, impl_action: 'check', impl_time: impl_time, is_new: od.is_new, is_delete: od.is_delete, is_dirty: od.is_dirty})
            when DeliveryState::REJECTED
              dlc.state = MovableState::REJECTED
              #*record dispatch
              impl_time = od.delivery_date.nil? ? od.created_at : od.delivery_date
              Record.create({recordable: dlc, destinationable: dlc.destinationable, impl_id: od.user_id, impl_user_type: ImplUserType::SENDER, impl_action: 'dispatch', impl_time: impl_time, is_new: od.is_new, is_delete: od.is_delete, is_dirty: od.is_dirty})
              #*record receive
              impl_time = od.received_date.nil? ? od.updated_at : od.received_date
              user_id = od.receiver_id.nil? ? default_receiver : od.receiver_id
              Record.create({recordable: dlc, destinationable: dlc.destinationable, impl_id: user_id, impl_user_type: ImplUserType::RECEIVER, impl_action: 'receive', impl_time: impl_time, is_new: od.is_new, is_delete: od.is_delete, is_dirty: od.is_dirty})
              #*record rejected
              impl_time = od.received_date.nil? ? od.updated_at : od.received_date
              user_id = od.receiver_id.nil? ? default_receiver : od.receiver_id
              Record.create({recordable: dlc, destinationable: dlc.destinationable, impl_id: user_id, impl_user_type: ImplUserType::REJECTOR, impl_action: 'reject', impl_time: impl_time, is_new: od.is_new, is_delete: od.is_delete, is_dirty: od.is_dirty})
          end
          #get all forklift and added to delivery
          dlc.created_at = od.created_at
          dlc.updated_at = od.updated_at
          dlc.is_new = od.is_new
          dlc.is_delete = od.is_delete
          dlc.is_dirty = od.is_dirty
          dlc.save
          #puts "#{d.id} => DC \n"
          #puts "#{dlc.id} => DLC \n"
          #puts "#{dlc.records.count} => DLC Records created! \n"
          od.forklifts.each do |of|
            #注意，这里只统计到了运单中的Forklift，但是没有统计到不存在晕但中的forklift
            f = Forklift.create({
                                    id: of.id,
                                    user_id: of.user_id,
                                    location_id: of.user.location_id,
                                    created_at: of.created_at,
                                    updated_at: of.updated_at,
                                    remark: of.remark,
                                    is_delete: of.is_delete,
                                    is_new: of.is_new,
                                    is_dirty: of.is_dirty
                                })
            flc = f.logistics_containers.build(source_location_id: of.user.location_id, user_id: of.user_id, destinationable: of.whouse)
            flc.des_location_id = destination.id if destination

            #set state
            #create records
            case of.state
              when ForkliftState::ORIGINAL
                flc.state = MovableState::INIT
              when ForkliftState::WAY
                flc.state = MovableState::WAY
                #record dispatch
                impl_time = of.created_at
                Record.create({recordable: flc, destinationable: flc.destinationable, impl_id: of.user_id, impl_user_type: ImplUserType::SENDER, impl_action: 'dispatch', impl_time: impl_time, is_new: of.is_new, is_delete: of.is_delete, is_dirty: of.is_dirty})
              when ForkliftState::DESTINATION
                flc.state = MovableState::ARRIVED
                #record dispatch
                impl_time = of.created_at
                Record.create({recordable: flc, destinationable: flc.destinationable, impl_id: of.user_id, impl_user_type: ImplUserType::SENDER, impl_action: 'dispatch', impl_time: impl_time, is_new: of.is_new, is_delete: of.is_delete, is_dirty: of.is_dirty})
                #record receive
                impl_time = of.updated_at
                Record.create({recordable: flc, destinationable: flc.destinationable, impl_id: user_id, impl_user_type: ImplUserType::RECEIVER, impl_action: 'receive', impl_time: impl_time, is_new: of.is_new, is_delete: of.is_delete, is_dirty: of.is_dirty})
              when ForkliftState::RECEIVED, ForkliftState::PART_RECEIVED
                flc.state = MovableState::CHECKED
                #record dispatch
                impl_time = of.created_at
                Record.create({recordable: flc, destinationable: flc.destinationable, impl_id: of.user_id, impl_user_type: ImplUserType::SENDER, impl_action: 'dispatch', impl_time: impl_time, is_new: of.is_new, is_delete: of.is_delete, is_dirty: of.is_dirty})
                #record receive
                impl_time = of.updated_at
                Record.create({recordable: flc, destinationable: flc.destinationable, impl_id: user_id, impl_user_type: ImplUserType::RECEIVER, impl_action: 'receive', impl_time: impl_time, is_new: of.is_new, is_delete: of.is_delete, is_dirty: of.is_dirty})
                #record check
                Record.create({recordable: flc, destinationable: flc.destinationable, impl_id: user_id, impl_user_type: ImplUserType::EXAMINER, impl_action: 'check', impl_time: impl_time, is_new: of.is_new, is_delete: of.is_delete, is_dirty: of.is_dirty})
            end

            dlc.add(flc)
            flc.created_at = of.created_at
            flc.updated_at = of.updated_at
            flc.is_new = of.is_new
            flc.is_delete = of.is_delete
            flc.is_dirty = of.is_dirty
            flc.save

            #puts "#{f.id} => FC \n"
            #puts "#{flc.id} => Fflc \n"
            #puts "#{flc.records.count} => Fflc Records \n"

            #packages
            of.packages.each do |op|
              fifo_time = nil
              begin
                fifo_time = Time.parse(op.check_in_time)
              rescue
                fifo_time = Time.now
              end
              p = Package.create({

RailsClient/app/views/deliveries/_form.html.erb
<%= form_for(@delivery, url: delivery_path) do |f| %>
    <% if @delivery.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@delivery.errors.count, "error") %> prohibited this delivery from being saved:</h2>

          <ul>
            <% @delivery.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="panel panel-default">
      <div class="panel-body">
        <!--<div class="col-sm-12" style="margin-left: 15px;">-->
          <!--<%= f.label :state, '状 态' %>-->
          <!--<%= f.select(:state, MovableState.state, {include_blank: false}, :style => 'width:150px;') %>-->

          <!--<span style="color: red;">*状态可以被修改，但是依然需要使用移动设备进行接收，否则不会产生操作记录</span>-->
        <!--</div>-->

        <div class="col-sm-12" style="margin-top: 10px;">
          <div class="col-sm-6">
            <%= f.label :des_location_id, '目的地' %>
            <%= f.select(:des_location_id, Location.all.collect { |l| [l.name, l.id] }, {include_blank: false}, :style => 'width:150px;') %>
          </div>
          <div class="col-sm-6">
            <%= f.label :remark, '备 注' %>
            <%= f.text_field :remark, :style => 'width:300px;' %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-12">
      <div class="col-sm-3" style="background: white;margin-left: -20px; margin-top: -20px;height: 50px;border-bottom-right-radius: 20px;box-shadow: 2px 4px 4px #999; ">
        <div class="actions" style="text-align: center;">
          <%= f.submit value: '提 交', class: 'btn btn-primary', :style => 'width:200px;margin-top:5px;' %>
        </div>
      </div>
    </div>
<% end %>

<script type="text/javascript">
    $(".datepicker").datetimepicker({
        lang: 'ch',
        format: 'Y-m-d H:i'
    })
</script>

RailsClient/app/views/deliveries/import.html.erb
<script type="text/javascript">
    $(function () {
        data_upload("#item-data-uploader", 'json');
    });
</script>

<p id="notice">
  <%= notice %>
</p>
<h3>导入运单</h3>
<div>
  选择数据文件
  <input id="item-data-uploader" type="file" name="files[]" data-url="/deliveries/import">
  <div class="abstractblock" id="item-data-uploader-preview" style="display:none;"></div>
</div>
<%= link_to '返回', deliveries_path %>

RailsClient/app/views/deliveries/index.html.erb
<style>
    .col-sm-12 {
        height: 40px;
    }

    select {
        min-width: 150px;
    }

    .up_search {
        text-align: center;
        cursor: pointer;
    }

    .IconA {
        margin: 0 10px;
        font-size: 1.2em;
    }

    .IconA:hover {
        text-decoration: none;
        background-color: white;
    }

    .table > thead > tr > th, .table > tbody > tr > td {
        text-align: center;
    }

    a:hover, a:active {
        text-decoration: none;
        background-color: white;
        color: black;
        outline: none;
    }
</style>

<div class="panel panel-default">
  <ol class="breadcrumb" style="background: transparent;padding: 20px 0 0 20px;font-size: 1.2em;">
    <li class="active">运输管理</li>
    <li class="active">发运流程</li>
    <li class="active">运单</li>
  </ol>
</div>

<div class="all-search">
  <form method="get" action="<%= send("search_logistics_containers_path") %>">
    <div class="col-sm-12">
      <div class="col-sm-3">
        运单号：
        <input type="text" name="delivery[container_id]" value="<%= @delivery_container_id %>"/>
        <input type="hidden" name="delivery[container_id_fuzzy]"/>
      </div>

      <div class="col-sm-3">
        创建员工号：
        <input type="text" name="delivery[user_id]" value="<%= @delivery_user_id %>"/>
      </div>

      <div class="col-sm-3">
        运单状态：
        <%= select 'delivery', 'state', MovableState.state, selected: @delivery_state, include_blank: true %>
      </div>
    </div>

    <div class="col-sm-12">
      <% if !current_user.is_client_user? %>
          <div class="col-sm-3">
            发送地：
            <%= select_tag('delivery[source_location_id]', options_from_collection_for_select(Location.all, 'id', 'name', @delivery_source_location_id), include_blank: true) %>
          </div>

          <div class="col-sm-3">
            目的地：
            <%= select_tag('delivery[des_location_id]', options_from_collection_for_select(Location.all, 'id', 'name', @delivery_des_location_id), include_blank: true) %>
          </div>

      <% end %>
      <div class="col-sm-6">
        创建日期：
        <input type="text" name="delivery[created_at][start]" class="datepicker" value="<%= @delivery_created_at_start %>"/>
        ~
        <input type="text" name="delivery[created_at][end]" class="datepicker" value="<%= @delivery_created_at_end %>"/>
      </div>
    </div>

    <div class="col-sm-12" style="border-bottom: 1px solid #ccc;margin-bottom: 10px;">
      <div class="col-sm-3">
        员工号：
        <input type="text" name="records[impl_id]" value="<%= @records_impl_id %>"/>
      </div>
      <div class="col-sm-3">
        操 作：
        <%= select 'records', 'impl_user_type', ImplUserType.list_action_menu, selected: @records_impl_user_type, include_blank: true %>
      </div>
      <div class="col-sm-6">
        时  间：
        <input type="text" name="records[impl_time][start]" class="datepicker" value="<%= @records_impl_time_start %>"/>
        ~ <input type="text" name="records[impl_time][end]" class="datepicker" value="<%= @records_impl_time_end %>"/>
      </div>
    </div>

     <div class="col-sm-12">
        <input type="hidden" value="delivery" name="model"/>
        <input type="hidden" value="records" name="tables"/><!--使用分号隔开，这里的表应该与上面的参数一致-->
        <div class="col-sm-4">
          <input type="submit" value="查找" class="btn btn-primary" name="search" style="width: 200px;"/>
        </div>
        <div class="col-sm-4">
          <input type="submit" value="导出" class="btn btn-primary" name="download" style="width: 200px;"/>
        </div>

        <div class="col-sm-4">
          <input type="button" value="打印发运单" class='btn btn-warning' onclick="print_delivery_list();"/>
        </div>
    </div>
  </form>
</div>

<div class="col-sm-12 up_search">
  <i class=" glyphicon glyphicon-chevron-up pull-right" title="收起搜索条件"></i>
</div>

<!-- 
<div class="col-sm-12" style="margin-bottom: 20px;margin-top: -20px; ">
  <div class="col-sm-2">
    <input type="button" value="打印发运单" class='btn btn-warning' onclick="print_delivery_list();"/>
  </div>
  <div class="col-sm-2">
    <input type="button" value="打印接收确认单" class='btn btn-info' onclick="print_delivery_confirm_list();"/>
  </div>
  <div class="col-sm-2">
    <input type="button" value="打印未接收清单" class='btn btn-success' onclick="print_delivery_unrece_list();"/>
  </div>
  <div class="col-sm-2">
    <input type="button" value="打印接收清单" class='btn btn-primary' onclick="print_delivery_reve_list();"/>
  </div>
  <div class="col-sm-2">
    <% if current_user.can_edit_inventory? %>
        <%= link_to '导入离线运单', import_logistics_containers_path, :class => "btn btn-warning", :style => 'color:white;' %>
    <% end %>
  </div>
</div>
 -->
<div class="col-sm-12">
  <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @deliveries %>
    </div>
    <%= will_paginate @deliveries, :container => false %>
  </div>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead>
  <tr>
    <th></th>
    <!--基础-->
    <th>NO.</th>
    <th>运单号</th>
    <th>批次号</th>
    <th>状态</th>
    <th>目的地</th>
    <th>创建员工号</th>
    <th>备注</th>
    <!--基础-->
    <!--包含-->
    <th>托清单数</th>
    <% if current_user.location.check_delivery_by_pick %>
        <th>
          需求单号
        </th>
    <% end %>
    <!--包含-->
    <!--操作-->
    <th>最新记录</th>
    <!--操作-->
    <th>木盘数</th>
    <th>纸箱数</th>
    <th>NPS数</th>
    <th colspan="3">操作</th>
  </tr>
  </thead>

  <tbody>
  <% @deliveries.each_with_index do |delivery, index|
    delivery_presenter=DeliveryPresenter.new(delivery)
  %>
      <tr>
        <td><input type="checkbox" id="<%= delivery.id %>" class='print-check'></td>
        <td><%= index+@deliveries.offset+1 %></td>
        <td><%= delivery.container_id %></td>
        <td><%=delivery.batch_nr%></td>
        <td><%= delivery.state_display %></td>
        <td><%= delivery.destination.name %></td>
        <td><%= delivery.user.nr %></td>
        <td><%= delivery.remark %></td>
        <td>
          <%= link_to delivery_presenter.forklifts.count, forklifts_delivery_path(delivery), style: 'border-radius:10px;padding:5px 20px 5px 20px;background:steelblue;color:white;', :title => '托清单数' %>
        </td>
        <% if current_user.location.check_delivery_by_pick %>
            <td title="<%= delivery.order_id %>">
              <% if delivery.order %>
                  <%= link_to content_tag(:span, delivery.order_id, :class => 'label label-primary'), order_items_order_path(delivery.order) %>
              <% end %>
            </td>
        <% end %>
        <td>
          <%= delivery.get_records.last.display %>
        </td>
        <td><%= delivery.part_type_count[:wooden] %></td>
        <td><%= delivery.part_type_count[:box]  %></td>
        <td><%= delivery.part_type_count[:nps]  %></td>

        <td>
          <%= link_to content_tag(:i, '', :class => 'glyphicon glyphicon-eye-open', :style => 'color:green;'), {controller: 'deliveries', action: 'show', id: delivery.id}, :class => 'IconA', :title => '运单详情' %>

          <% if current_user.permission?(:operate_delivery) %>
              <%= link_to content_tag(:i, '', :class => 'glyphicon glyphicon-pencil', :style => 'color:#4F94CD;'), {controller: 'deliveries', action: 'edit', id: delivery.id}, class: 'IconA', :title => '编辑运单' %>
          <% end %>

          <%= link_to content_tag(:i, '', :class => 'glyphicon glyphicon-trash', :style => 'color:darkred;'), {controller: 'deliveries', action: 'destroy', id: delivery.id}, method: :delete, data: {confirm: '确认删除?'}, :class => 'IconA', :title => '删除' %>

          <!--<%= link_to content_tag(:i, '', :class => 'glyphicon glyphicon-log-out'), {controller: 'logistics_containers', action: 'destroy', id: delivery.id}, class: 'IconA', :title => '导出运单' %>-->
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<div class="digg_pagination">
  <%= will_paginate @deliveries, :container => false %>
</div>

<script>
    $(function () {
        $(".datepicker").datetimepicker({
            lang: 'ch',
            format: 'Y-m-d H:i'
        });
    });
    init_check();

    $('.up_search').click(function () {
        var this_arrow = $(this);
        $('.all-search').slideToggle(300, function () {
            if (this_arrow.children('i').hasClass('glyphicon-chevron-up')) {
                this_arrow.children('i').attr('class', 'glyphicon glyphicon-chevron-down pull-right');
                this_arrow.children('i').attr('title', '展开搜索条件');
            } else {
                this_arrow.children('i').attr('class', 'glyphicon glyphicon-chevron-up pull-right');
                this_arrow.children('i').attr('title', '收起搜索条件');
            }
        });
    })
</script>

RailsClient/app/views/deliveries/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', deliveries_path %>